-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE CLIENTES (
ID_CLIENTE INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
NASCIMENTO_CLIENTE DATETIME,
TELEFONE_CLIENTE VARCHAR(14),
EMAIL VARCHAR(70),
CPF VARCHAR(14),
NOME_CLIENTE VARCHAR(50)
)

CREATE TABLE AUTORES (
ID_AUTOR INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOME_AUTOR VARCHAR(50),
NACIONALIDADE_AUTOR VARCHAR(50),
NASCIMENTO_AUTOR DATETIME
)

CREATE TABLE EDITORAS (
ID_EDITORA INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
CNPJ VARCHAR(18),
CIDADE VARCHAR(50),
NOME_EDITORA VARCHAR(50),
ENDERECO VARCHAR(100),
TELEFONE_EDITORA VARCHAR(14),
REDE_SOCIAL VARCHAR(50)
)

CREATE TABLE LIVROS+VENDAS (
ID_LIVRO INT AUTO_INCREMENT NOT NULL,
TITULO VARCHAR(50),
AUTOR VARCHAR(50),
EDITORA VARCHAR(50),
GENERO VARCHAR(30),
PRECO DECIMAL,
QUANTIDADE INT,
ID_VENDA INT AUTO_INCREMENT NOT NULL,
DATA_VENDA DATETIME,
VALOR_TOTAL DECIMAL,
PRIMARY KEY(ID_LIVRO,ID_VENDA)
)

CREATE TABLE PUBLICA (
ID_EDITORA INT AUTO_INCREMENT NOT NULL,
ID_LIVRO INT AUTO_INCREMENT NOT NULL,
FOREIGN KEY(ID_EDITORA) REFERENCES EDITORAS (ID_EDITORA),
FOREIGN KEY(/*erro: ??*/) REFERENCES LIVROS+VENDAS (ID_LIVRO,ID_VENDA)
)

CREATE TABLE ESCREVE (
ID_AUTOR INT AUTO_INCREMENT NOT NULL,
ID_LIVRO INT AUTO_INCREMENT NOT NULL,
FOREIGN KEY(ID_AUTOR) REFERENCES AUTORES (ID_AUTOR),
FOREIGN KEY(/*erro: ??*/) REFERENCES LIVROS+VENDAS (ID_LIVRO,ID_VENDA)
)

CREATE TABLE GERAM (
ID_CLIENTE INT AUTO_INCREMENT NOT NULL,
ID_VENDA INT AUTO_INCREMENT NOT NULL,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE),
FOREIGN KEY(/*erro: ??*/) REFERENCES LIVROS+VENDAS (ID_LIVRO,ID_VENDA)
)

