-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.

CREATE DATABASE LIVRARIA;

USE LIVRARIA;

CREATE TABLE CLIENTES (
  ID_CLIENTE INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  NASCIMENTO_CLIENTE DATETIME,
  TELEFONE_CLIENTE VARCHAR(14),
  EMAIL VARCHAR(70),
  CPF VARCHAR(14),
  NOME_CLIENTE VARCHAR(50)
);

CREATE TABLE AUTORES (
  ID_AUTOR INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  NOME_AUTOR VARCHAR(50),
  NACIONALIDADE_AUTOR VARCHAR(50),
  NASCIMENTO_AUTOR DATETIME
);

CREATE TABLE EDITORAS (
  ID_EDITORA INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  CNPJ VARCHAR(18),
  CIDADE VARCHAR(50),
  NOME_EDITORA VARCHAR(50),
  ENDERECO VARCHAR(100),
  TELEFONE_EDITORA VARCHAR(14),
  REDE_SOCIAL VARCHAR(50)
);

CREATE TABLE LIVROS (
  ID_LIVRO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  TITULO VARCHAR(50),
  GENERO VARCHAR(30),
  PRECO DECIMAL(10,2),
  QUANTIDADE INT
);

CREATE TABLE VENDAS (
  ID_VENDA INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  DATA_VENDA DATETIME,
  VALOR_TOTAL DECIMAL(10,2),
  ID_CLIENTE INT NOT NULL,
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

-- Relação N:N entre EDITORAS e LIVROS
CREATE TABLE PUBLICA (
  ID_EDITORA INT NOT NULL,
  ID_LIVRO INT NOT NULL,
  PRIMARY KEY(ID_EDITORA, ID_LIVRO),
  FOREIGN KEY(ID_EDITORA) REFERENCES EDITORAS(ID_EDITORA),
  FOREIGN KEY(ID_LIVRO) REFERENCES LIVROS(ID_LIVRO)
);

-- Relação N:N entre AUTORES e LIVROS
CREATE TABLE ESCREVE (
  ID_AUTOR INT NOT NULL,
  ID_LIVRO INT NOT NULL,
  PRIMARY KEY(ID_AUTOR, ID_LIVRO),
  FOREIGN KEY(ID_AUTOR) REFERENCES AUTORES(ID_AUTOR),
  FOREIGN KEY(ID_LIVRO) REFERENCES LIVROS(ID_LIVRO)
);

-- Relação N:N entre VENDAS e LIVROS
CREATE TABLE VENDA_CONTEM_LIVROS (
  ID_VENDA INT NOT NULL,
  ID_LIVRO INT NOT NULL,
  QUANTIDADE INT NOT NULL,
  PRIMARY KEY(ID_VENDA, ID_LIVRO),
  FOREIGN KEY(ID_VENDA) REFERENCES VENDAS(ID_VENDA),
  FOREIGN KEY(ID_LIVRO) REFERENCES LIVROS(ID_LIVRO)
);

INSERT INTO CLIENTES (NASCIMENTO_CLIENTE, TELEFONE_CLIENTE, EMAIL, CPF, NOME_CLIENTE)
VALUES 
('1995-06-15', '(11)91234-5678', 'joao.silva@email.com', '123.456.789-00', 'João da Silva'),
('1988-02-20', '(21)99876-5432', 'maria.souza@email.com', '987.654.321-00', 'Maria Souza');

INSERT INTO AUTORES (NOME_AUTOR, NACIONALIDADE_AUTOR, NASCIMENTO_AUTOR)
VALUES 
('Machado de Assis', 'Brasileiro', '1839-06-21'),
('George Orwell', 'Britânico', '1903-06-25');

INSERT INTO EDITORAS (CNPJ, CIDADE, NOME_EDITORA, ENDERECO, TELEFONE_EDITORA, REDE_SOCIAL)
VALUES
('12.345.678/0001-99', 'São Paulo', 'Editora Moderna', 'Av. Paulista, 1000', '(11)4002-8922', '@editoramoderna'),
('98.765.432/0001-11', 'Rio de Janeiro', 'Editora Clássicos', 'Rua das Letras, 200', '(21)3555-6677', '@editoraclassicos');

INSERT INTO LIVROS (TITULO, GENERO, PRECO, QUANTIDADE)
VALUES
('Dom Casmurro', 'Romance', 45.90, 100),
('1984', 'Ficção Distópica', 59.90, 50);




