CREATE DATABASE SENAI;

USE SENAI;

CREATE TABLE ALUNOS (
ID_ALUNO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOME_ALUNO VARCHAR(70),
EMAIL_ALUNO VARCHAR(70) NOT NULL,
NASCIMENTO_ALUNO DATETIME
);

CREATE TABLE CURSOS (
ID_CURSO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
TITULO VARCHAR(70),
DESCRICAO VARCHAR(255),
CARGA_HORARIA INT,
STATUS VARCHAR(20)
);

CREATE TABLE INSCRICOES (
ID_INSCRICAO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
DATA_INSCRICAO DATETIME,
ID_ALUNO INT AUTO_INCREMENT NOT NULL,
ID_CURSO INT AUTO_INCREMENT NOT NULL,
FOREIGN KEY(ID_ALUNO) REFERENCES ALUNOS (ID_ALUNO),
FOREIGN KEY(ID_CURSO) REFERENCES CURSOS (ID_CURSO)
);

CREATE TABLE AVALIACOES (
ID_AVALIACAO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOTA DECIMAL,
COMENTARIO VARCHAR(255),
ID_INSCRICAO INT AUTO_INCREMENT NOT NULL,
FOREIGN KEY(ID_INSCRICAO) REFERENCES INSCRICOES (ID_INSCRICAO)
);
