-- CRIAÇÃO DO BANCO
CREATE DATABASE SENAI;
USE SENAI;

-- TABELAS
CREATE TABLE ALUNOS (
  ID_ALUNO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  NOME_ALUNO VARCHAR(70),
  EMAIL_ALUNO VARCHAR(70) NOT NULL,
  NASCIMENTO_ALUNO DATETIME
);

CREATE TABLE CURSOS (
  ID_CURSO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  TITULO VARCHAR(70),
  DESCRICAO VARCHAR(255),
  CARGA_HORARIA INT,
  STATUS VARCHAR(20)
);

CREATE TABLE INSCRICOES (
  ID_INSCRICAO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  DATA_INSCRICAO DATETIME,
  ID_ALUNO INT NOT NULL,
  ID_CURSO INT NOT NULL,
  FOREIGN KEY(ID_ALUNO) REFERENCES ALUNOS (ID_ALUNO),
  FOREIGN KEY(ID_CURSO) REFERENCES CURSOS (ID_CURSO)
);

CREATE TABLE AVALIACOES (
  ID_AVALIACAO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  NOTA DECIMAL(3,1),
  COMENTARIO VARCHAR(255),
  ID_INSCRICAO INT NOT NULL,
  FOREIGN KEY(ID_INSCRICAO) REFERENCES INSCRICOES (ID_INSCRICAO)
);

-- INSERTS
INSERT INTO ALUNOS (NOME_ALUNO, EMAIL_ALUNO, NASCIMENTO_ALUNO) VALUES
('João', 'joao@email.com', '2000-05-10'),
('Maria', 'maria@email.com', '1999-08-22'),
('Carlos', 'carlos@email.com', '2001-01-15'),
('Ana', 'ana@email.com', '2002-11-30'),
('Pedro', 'pedro@email.com', '1998-07-07');

INSERT INTO CURSOS (TITULO, DESCRICAO, CARGA_HORARIA, STATUS) VALUES
('Introdução à Programação', 'Curso básico de lógica', 40, 'ativo'),
('Banco de Dados', 'Curso sobre modelagem e SQL', 80, 'ativo'),
('Desenvolvimento Web', 'Curso sobre HTML, CSS e JavaScript', 160, 'inativo'),
('Redes de Computadores', 'Fundamentos de redes', 80, 'ativo'),
('Manutenção de Computadores', 'Curso de hardware', 40, 'inativo');

INSERT INTO INSCRICOES (DATA_INSCRICAO, ID_ALUNO, ID_CURSO) VALUES
('2025-01-15', 1, 1),
('2025-01-20', 2, 2),
('2025-02-05', 3, 3),
('2025-02-10', 4, 4),
('2025-02-15', 5, 5);

INSERT INTO AVALIACOES (NOTA, COMENTARIO, ID_INSCRICAO) VALUES
(8.5, 'MUITO BEM.', 1),
(9.0, 'ÓTIMO, CONTINUE ASSIM.', 2),
(7.5, 'BOM.', 3);

-- UPDATES
UPDATE ALUNOS
SET EMAIL_ALUNO = 'gabriel.ramos@email.com'
WHERE ID_ALUNO = 5;

UPDATE CURSOS
SET CARGA_HORARIA = 100
WHERE ID_CURSO = 3;

UPDATE ALUNOS
SET NOME_ALUNO = 'Gabriel Ramos'
WHERE ID_ALUNO = 5;

UPDATE CURSOS
SET STATUS = 'inativo'
WHERE ID_CURSO = 3;

UPDATE AVALIACOES
SET NOTA = 8.0
WHERE ID_AVALIACAO = 3;

-- DELETES
DELETE FROM INSCRICOES
WHERE ID_INSCRICAO = 2;

DELETE FROM CURSOS
WHERE ID_CURSO = 4;

DELETE FROM AVALIACOES
WHERE ID_AVALIACAO = 3;

DELETE FROM ALUNOS
WHERE ID_ALUNO = 5;

DELETE FROM INSCRICOES
WHERE ID_CURSO = 5;

-- SELECTS
SELECT * FROM ALUNOS;

SELECT NOME_ALUNO, EMAIL_ALUNO
FROM ALUNOS;

SELECT * FROM CURSOS
WHERE CARGA_HORARIA > 30;

SELECT * FROM CURSOS
WHERE STATUS = 'inativo';

SELECT * FROM ALUNOS
WHERE YEAR(NASCIMENTO_ALUNO) > 1995;

SELECT * FROM AVALIACOES
WHERE NOTA > 9;

SELECT COUNT(*) AS TOTAL_CURSOS
FROM CURSOS;

SELECT TITULO, CARGA_HORARIA
FROM CURSOS
ORDER BY CARGA_HORARIA DESC
LIMIT 3;
